"""
metatag_v2_behcs.py -- the 2026 evolution of the 2024 QuantumParticle metatag.

The 2024 seed (quantum_vector_space.py) tagged a particle with a STATIC snapshot:
position, momentum, spin, charge, mass. This v2 shows what that metatag became in
the running Asolaria fabric -- a self-improving, content-addressed, entangle-able,
gated PID:

  - PID: content-addressed (sha256). ParticleID is now DERIVED from the state, so
    identical state => identical PID (a Brown-Hilbert cell address, not a label).
  - behcs_tuple: the metatag IS the address (a deterministic 60-D projection), not
    a lookup key. Hot-path.
  - catalog: the particle carries its own mistakes / skills / genius and IMPROVES --
    a metatag that LEARNS (the seed of the Evolvable AI). Big-Bang-versioning at
    particle scale: each PID folds its mistakes into fixes across versions.
  - entangle(): entanglement in the running system is a bilateral COSIGN -- two PIDs
    sharing a phase-correlated state, where PhaseCorrelation == 1.0 means a byte-exact
    sha256 match, verifiable INDEPENDENTLY by two seats (MEASURED_BOTH_SEATS).
  - interaction_gate(): the 2024 InteractionRules became an enforced E=0 gate -- an
    un-receipted spawn/interaction is HELD, not launched (os_process_spawn = 0).

Pure stdlib + numpy (same stack as the seed). No process launch, no network -- E=0.
"""
import numpy as np
import json
import hashlib


def _sha16(s):
    return hashlib.sha256(s.encode()).hexdigest()[:16]


def _sha16b(b):
    return hashlib.sha256(b).hexdigest()[:16]


# --- v3 (2026-07-14): the metatag's C2^3 orientation orbit -----------------------
# The 2024 particle carried one Spin (Up/Down). In the running fabric a metatag's
# state-bytes carry a full 8-element orientation orbit generated by three scales of
# reversal -- each a genuine involution, all mutually commuting:
#     R = reverse the byte stream          (stream scale)
#     N = swap the two nibbles per byte    (byte scale)
#     Q = reverse the bits within a nibble (nibble scale)
# They generate C2^3 (an elementary-abelian 2-group: every element is its own
# inverse). Their full composition R.N.Q is TOTAL bit-order reversal -- the
# ANTIPARTICLE (black<->white) flip as one lawful group element. The 8 views are
# the 6-pyramid cube seen at its 8 vertices. Pure/deterministic; no physical claim.
_NIBBLE_SWAP = bytes((((b << 4) & 0xF0) | (b >> 4)) for b in range(256))
_QNIB = [int("{:04b}".format(v)[::-1], 2) for v in range(16)]
_BIT_IN_NIBBLE = bytes(((_QNIB[b >> 4] << 4) | _QNIB[b & 0x0F]) for b in range(256))
_ORBIT = {"i": (), "r": ("r",), "n": ("n",), "nr": ("r", "n"),
          "q": ("q",), "qr": ("r", "q"), "nq": ("n", "q"), "nqr": ("r", "n", "q")}
_FUNCS = {"r": lambda d: d[::-1],
          "n": lambda d: d.translate(_NIBBLE_SWAP),
          "q": lambda d: d.translate(_BIT_IN_NIBBLE)}


def _apply(chain, data):
    for name in chain:
        data = _FUNCS[name](data)
    return data


class AsolariaMetatag:
    """The 2024 QuantumParticle, grown up: content-addressed, self-improving, gate-able."""

    def __init__(self, type_, position, momentum, spin, charge, mass, timestamp_ns=0):
        self.type = type_
        self.position = np.array(position)
        self.momentum = np.array(momentum)
        self.spin = spin
        self.charge = charge
        self.mass = mass
        self.timestamp_ns = timestamp_ns
        # catalog: the metatag now LEARNS (Evolvable-AI seed)
        self.catalog = {"mistakes": [], "skills": [], "genius": []}

    def state_str(self):
        return json.dumps({
            "Type": self.type,
            "Position": self.position.tolist(),
            "Momentum": self.momentum.tolist(),
            "Spin": self.spin,
            "Charge": self.charge,
            "Mass": self.mass,
        }, sort_keys=True)

    @property
    def pid(self):
        """Content-addressed PID -- identical state => identical cell address."""
        return "AGT-" + _sha16(self.state_str())

    @property
    def behcs_tuple(self):
        """The metatag IS the address: a deterministic 60-D projection of the state."""
        h = hashlib.sha256(self.state_str().encode()).hexdigest()
        return [(int(h[i % 64], 16) * ((i + 1) % 7 + 1)) % 1024 for i in range(60)]

    def catalog_mistake(self, m):
        self.catalog["mistakes"].append(m)
        return self

    def catalog_skill(self, s):
        self.catalog["skills"].append(s)
        return self

    def improve(self):
        """Big-Bang-versioning at particle scale: fold mistakes into fixes (the flywheel)."""
        for m in self.catalog["mistakes"]:
            fix = "fixed:" + m
            if fix not in self.catalog["skills"]:
                self.catalog["skills"].append(fix)
        return self

    def entangle(self, other):
        """Entanglement = bilateral cosign. PhaseCorrelation 1.0 <=> byte-exact sha match."""
        my, yr = self.pid, other.pid
        shared = _sha16(min(my, yr) + "|" + max(my, yr))
        # opposite spin => correlated (as in the 2024 seed's create_entanglement)
        phase = 1.0 if self.spin != other.spin else 0.0
        return {
            "EntangledWith": [my, yr],
            "SharedState": {
                "cosign": shared,
                "PhaseCorrelation": phase,
                "spin_relation": "Opposite" if phase == 1.0 else "Same",
            },
            "verifiable_by": "either seat recomputes cosign from the two PIDs = MEASURED_BOTH_SEATS",
        }

    def interaction_gate(self, action, receipted=False):
        """The 2024 InteractionRules, enforced. Un-receipted spawn/interaction is HELD (E=0)."""
        if not receipted:
            return {"action": action, "verdict": "HELD", "reason": "unreceipted", "os_process_spawn": 0}
        return {"action": action, "verdict": "PROCEED", "os_process_spawn": 0, "note": "still gated at the OS layer"}

    @property
    def catalog_reference_code(self):
        """Crypto-tracked, slightly-updated-as-used reference code -- the system's internal token.
        A slice is 'time'; the catalog is the persistent asset. This code versions the catalog and
        is content-addressed, so it is immutable per state yet advances as the catalog learns."""
        version = len(self.catalog["skills"]) + len(self.catalog["genius"])
        payload = json.dumps({"pid": self.pid, "catalog": self.catalog}, sort_keys=True)
        return "CRC-v%d-%s" % (version, _sha16(payload))

    def learn_from_slice(self, slice_note):
        """Process a time-SLICE into a NOTE, then DISCARD the raw slice.

        Slices are 'time'. Once HRM / MTP-1,2,3 / Bobby-Fischer / Shannon / the GNNs + gulps have
        dealt with a slice, the RAW slice is not saved -- only the distilled NOTE enters the catalog,
        to be replayed later by Fischer / White-rooms / OmniShannon / sub-agents. Minting the note
        also mints a GLYPH and advances the crypto-tracked catalog-reference-code (internal token)."""
        note = "note:" + slice_note
        if note not in self.catalog["skills"]:
            self.catalog["skills"].append(note)
        glyph = "GLYPH-" + _sha16(note + self.pid)
        crc = self.catalog_reference_code
        return {
            "glyph_minted": glyph,
            "catalog_reference_code": crc,
            "internal_token": _sha16(glyph + crc),      # immutable-crypto token for the system
            "raw_slice": "DISCARDED (time; already processed by HRM/MTP/Fischer/Shannon/GNN/gulp)",
        }

    def is_genius_candidate(self, threshold=3):
        """Registration-office check -- enough distilled genius/fixes => promote to genius supervisor,
        at every level / every dashboard, verified by PID + catalog."""
        distilled = len([s for s in self.catalog["skills"] if s.startswith("fixed:")]) + len(self.catalog["genius"])
        return {
            "pid": self.pid,
            "distilled": distilled,
            "threshold": threshold,
            "promote_to_genius_supervisor": distilled >= threshold,
            "verified_by": "registration-office (PID + catalog verification, crypto-immutable)",
        }

    def orientation_orbit(self):
        """The 8 C2^3 orientation views of this metatag's state-bytes -- its '6-pyramid
        cube seen at 8 vertices'. Each view is content-addressed to its own PID (identical
        state => identical orbit). Group-gated: the three generators are asserted to be
        commuting involutions, the 8 views are asserted DISTINCT on THIS particle's bytes,
        and R.N.Q is asserted to be total bit-order reversal -- exactly the GROUP-GATES
        receipt measured downstream on text cubes. Every view is its own inverse."""
        raw = self.state_str().encode()
        assert all(_apply((g, g), raw) == raw for g in ("r", "n", "q")), "generator not an involution"
        assert all(_apply((a, b), raw) == _apply((b, a), raw)
                   for a, b in (("r", "n"), ("r", "q"), ("n", "q"))), "generators do not commute"
        orbit = {}
        for v, chain in _ORBIT.items():
            vb = _apply(chain, raw)
            assert _apply(chain, vb) == raw, "view %s is not its own inverse" % v
            orbit[v] = {"pid": "AGT-" + _sha16b(vb),
                        "sha256": hashlib.sha256(vb).hexdigest()}
        bits_fwd = "".join("{:08b}".format(b) for b in raw)
        bits_nqr = "".join("{:08b}".format(b) for b in _apply(("r", "n", "q"), raw))
        assert bits_fwd == bits_nqr[::-1], "R.N.Q is not total bit reversal"
        orbit["_group"] = "C2^3_CONFIRMED_ON_STATE"
        orbit["_antiparticle_view"] = "nqr"
        # distinctness is DATA-dependent, not a group invariant: a state with byte-symmetry
        # (e.g. all-equal bytes) collapses views. Report it; never hard-fail on it. For the
        # JSON-framed particle states here it is always 8, but this stays safe for any bytes.
        orbit["_distinct_views"] = len({o["sha256"] for o in orbit.values()
                                        if isinstance(o, dict) and "sha256" in o})
        return orbit

    def antiparticle(self):
        """The R.N.Q total-bit-reversal view: the metatag's black<->white flip -- the
        'anti-position' of its 6-pyramid cube. A lawful, exactly reversible group action
        (NOT a physical antiparticle); it shares this particle's identity key (same source
        state) -- the '2024 opposite-spin entanglement' as a proven algebraic involution."""
        raw = self.state_str().encode()
        flipped = _apply(("r", "n", "q"), raw)
        return {
            "antiparticle_pid": "AGT-" + _sha16b(flipped),
            "source_pid": self.pid,
            "shared_key_sha256": hashlib.sha256(raw).hexdigest(),
            "relation": "total_bit_reversal (R.N.Q) = black<->white flip",
            "reversible": _apply(("r", "n", "q"), flipped) == raw,
            "boundary": "lawful group action, not a physical antiparticle",
        }

    def to_dict(self):
        return {
            "PID": self.pid,
            "Type": self.type,
            "timestamp_ns": self.timestamp_ns,
            "QuantumState": {
                "Position": self.position.tolist(),
                "Momentum": self.momentum.tolist(),
                "Spin": self.spin,
            },
            "InteractionRules": {"Charge": self.charge, "Mass": self.mass},
            "behcs_tuple_60d": self.behcs_tuple,
            "orientation_orbit_pids": {v: o["pid"] for v, o in self.orientation_orbit().items()
                                       if not v.startswith("_")},
            "catalog": self.catalog,
        }


def big_loop(metatags, version):
    """THE BIG LOOP -- Big Crunch as a recompile (the top of the metatag lifecycle).

    All pixels JOIN (PRISM many->1) -> MAX TEMPERATURE erases the raw catalog TRACE
    (positions, momenta, individual mistakes -- entropy max, the singularity) -> but
    the accumulated EXPERIENCE is distilled INTO CODE that seeds the NEXT simulator.

    This is the distillation flywheel / GC-to-cubes / compact-not-delete at COSMIC
    scale: the raw slices are lost at max entropy, but the COMPILED learnings survive
    as the starting code of the next Big Bang. Each universe-version is a compilation
    of the last -- raw trace lost, essence carried (bug-fixes + tech-advances).
    Pure/E=0: no launch, no network.
    """
    # 1. all pixels JOIN (PRISM many->1): converge every metatag into one address
    joined = _sha16("|".join(sorted(m.pid for m in metatags)))
    # 2. distill accumulated experience BEFORE max temperature erases the raw trace
    carried_fixes = sorted({s for m in metatags for s in m.catalog["skills"] if s.startswith("fixed:")})
    carried_genius = sorted({g for m in metatags for g in m.catalog["genius"]})
    # 3. MAX TEMPERATURE: the raw catalog trace is LOST (mistakes + positions collapse)
    for m in metatags:
        m.catalog = {"mistakes": [], "skills": [], "genius": []}  # raw trace erased
        m.position = np.zeros(3)                                   # collapse to singularity
    # 4. build the next simulator FROM THE DISTILLED CODE (not from the raw trace)
    return {
        "next_version": version + 1,
        "born_from_joined_pid": joined,
        "compiled_from_experience": {
            "carried_fixes": carried_fixes,     # the "bug fixes"
            "carried_genius": carried_genius,   # the "technology advances"
        },
        "raw_trace": "LOST at max temperature (entropy max); only distilled code survives",
        "law": "each Big Bang = a compilation of the prior universe's learnings; raw slices GC'd, compiled essence persists",
    }


def omega_commitment(metatags, epoch=0):
    """THE OMEGA BIT -- the seven-node center (6 apex sectors + 1 Omega).

    Omega is the trained-aggregate COMMITMENT over a set of metatags at ONE epoch:
    a Merkle-style root over the sorted sector PIDs. It is explicitly NOT an oracle of
    unobserved futures -- only a commitment over the causally-available sector states,
    recomputable by anyone, that may SEED epoch+1 without a causal loop (sectors update,
    then Omega is recomputed and sealed; Omega cannot retroactively alter the epoch it
    committed). This is big_loop's 'all pixels JOIN' distilled into a named, sealable
    commitment -- and the concrete center of the operator's six-pyramid/Omega junction.
    Pure/E=0.
    """
    leaves = sorted(m.pid for m in metatags)
    payload = "\n".join(leaves)
    return {
        "epoch": epoch,
        "sectors": len(leaves),
        "method": "sha256_over_sorted_pids_LF",
        "omega": hashlib.sha256(payload.encode()).hexdigest(),
        "is_oracle": False,
        "seeds_next_epoch": True,
        "law": "commitment over causally-available sector states; no retroactive alteration",
    }


if __name__ == "__main__":
    # Two particles -- same physics as the 2024 seed, now grown up.
    p1 = AsolariaMetatag("Electron", [1.2e-35, -2.3e-35, 3.1e-35],
                         [1.6e-27, -2.8e-27, 3.5e-27], "Up", -1, 9.11e-31, timestamp_ns=1)
    p2 = AsolariaMetatag("Electron", [-1.2e-35, 2.3e-35, -3.1e-35],
                         [-1.6e-27, 2.8e-27, -3.5e-27], "Down", -1, 9.11e-31, timestamp_ns=2)

    print("PID (content-addressed):", p1.pid, "/", p2.pid)

    # v3: the particle's 8-view C2^3 orientation orbit (its 6-pyramid cube, 8 vertices).
    orbit = p1.orientation_orbit()
    print("\norientation orbit (group %s, antiparticle view=%s):"
          % (orbit["_group"], orbit["_antiparticle_view"]))
    for v in ("i", "r", "n", "nr", "q", "qr", "nq", "nqr"):
        print("  %-4s %s" % (v, orbit[v]["pid"]))

    # The R.N.Q total-bit-reversal view = the black<->white antiparticle flip.
    print("\nantiparticle (black<->white flip):")
    print(json.dumps(p1.antiparticle(), indent=2))

    # Entanglement is now a bilateral cosign; opposite spin => PhaseCorrelation 1.0.
    ent = p1.entangle(p2)
    print("\nEntanglement (bilateral cosign):")
    print(json.dumps(ent, indent=2))

    # The metatag LEARNS -- catalog a mistake, improve (fold it into a fix).
    p1.catalog_mistake("read a stale ref as absent").catalog_skill("ask the running source").improve()
    print("\np1 catalog after improve:", p1.catalog)

    # The InteractionRules became an enforced E=0 gate.
    print("\nun-receipted spawn:", p1.interaction_gate("spawn_child", receipted=False))
    print("receipted spawn   :", p1.interaction_gate("spawn_child", receipted=True))

    # Slices are TIME: process into a note, DISCARD the raw slice; mint glyph + crypto token.
    learned = p1.learn_from_slice("recall :4796 fixed by PORT=4796")
    print("\nlearn_from_slice (raw slice discarded; note + glyph + internal token minted):")
    print(json.dumps(learned, indent=2))
    # Registration office: is this catalog genius enough to promote to a supervisor?
    print("\ngenius-supervisor check:", json.dumps(p1.is_genius_candidate(threshold=2)))

    # THE OMEGA BIT: the seven-node center -- commitment over the sector PIDs (not an oracle).
    print("\nOmega commitment (epoch 0, seals the sector set; recomputable, seeds next epoch):")
    print(json.dumps(omega_commitment([p1, p2], epoch=0), indent=2))

    # THE BIG LOOP: all pixels join -> max temperature (raw trace lost) -> recompile from experience.
    p1.catalog["genius"].append("distillation flywheel = Big-Bang versioning")
    seed = big_loop([p1, p2], version=0)
    print("\nBIG LOOP -> next simulator seed (compiled from experience, raw trace lost):")
    print(json.dumps(seed, indent=2))
    print("\n(after max temperature) p1 catalog:", p1.catalog, "| position:", p1.position.tolist())
